RANK_VAL = {
    "IRON Ⅳ": 1,
    "IRON Ⅲ": 2,
    "IRON Ⅱ": 3,
    "IRON Ⅰ": 4,
    "BRONZE Ⅳ": 5,
    "BRONZE Ⅲ": 6,
    "BRONZE Ⅱ": 7,
    "BRONZE Ⅰ": 8,
    "SILVER Ⅳ": 9,
    "SILVER Ⅲ": 10,
    "SILVER Ⅱ": 11,
    "SILVER Ⅰ": 12,
    "GOLD Ⅳ": 13,
    "GOLD Ⅲ": 14,
    "GOLD Ⅱ": 15,
    "GOLD Ⅰ": 16,
    "PLATINUM Ⅳ": 17,
    "PLATINUM Ⅲ": 18,
    "PLATINUM Ⅱ": 19,
    "PLATINUM Ⅰ": 20,
    "EMERALD Ⅳ": 21,
    "EMERALD Ⅲ": 22,
    "EMERALD Ⅱ": 23,
    "EMERALD Ⅰ": 24,
    "DIAMOND Ⅳ": 25,
    "DIAMOND Ⅲ": 26,
    "DIAMOND Ⅱ": 27,
    "DIAMOND Ⅰ": 28,
    "MASTER": 29,
    "GRANDMASTER": 34,
    "CHALLENGER": 38,
}

RANKS = [
    "IRON Ⅳ",
    "IRON Ⅲ",
    "IRON Ⅱ",
    "IRON Ⅰ",
    "BRONZE Ⅳ",
    "BRONZE Ⅲ",
    "BRONZE Ⅱ",
    "BRONZE Ⅰ",
    "SILVER Ⅳ",
    "SILVER Ⅲ",
    "SILVER Ⅱ",
    "SILVER Ⅰ",
    "GOLD Ⅳ",
    "GOLD Ⅲ",
    "GOLD Ⅱ",
    "GOLD Ⅰ",
    "PLATINUM Ⅳ",
    "PLATINUM Ⅲ",
    "PLATINUM Ⅱ",
    "PLATINUM Ⅰ",
    "EMERALD Ⅳ",
    "EMERALD Ⅲ",
    "EMERALD Ⅱ",
    "EMERALD Ⅰ",
    "DIAMOND Ⅳ",
    "DIAMOND Ⅲ",
    "DIAMOND Ⅱ",
    "DIAMOND Ⅰ",
    "MASTER",
    "GRANDMASTER",
    "CHALLENGER",
]