RANK_VAL = {
    "Iron Ⅳ": 1,
    "Iron Ⅲ": 2,
    "Iron Ⅱ": 3,
    "Iron Ⅰ": 4,
    "Bronze Ⅳ": 5,
    "Bronze Ⅲ": 6,
    "Bronze Ⅱ": 7,
    "Bronze Ⅰ": 8,
    "Silver Ⅳ": 9,
    "Silver Ⅲ": 10,
    "Silver Ⅱ": 11,
    "Silver Ⅰ": 12,
    "Gold Ⅳ": 13,
    "Gold Ⅲ": 14,
    "Gold Ⅱ": 15,
    "Gold Ⅰ": 16,
    "Platinum Ⅳ": 17,
    "Platinum Ⅲ": 18,
    "Platinum Ⅱ": 19,
    "Platinum Ⅰ": 20,
    "Emerald Ⅳ": 21,
    "Emerald Ⅲ": 22,
    "Emerald Ⅱ": 23,
    "Emerald Ⅰ": 24,
    "Diamond Ⅳ": 25,
    "Diamond Ⅲ": 26,
    "Diamond Ⅱ": 27,
    "Diamond Ⅰ": 28,
    "Master": 29,
    "Grandmaster": 34,
    "Challenger": 38,
}

RANKS = [
    "Iron Ⅳ",
    "Iron Ⅲ",
    "Iron Ⅱ",
    "Iron Ⅰ",
    "Bronze Ⅳ",
    "Bronze Ⅲ",
    "Bronze Ⅱ",
    "Bronze Ⅰ",
    "Silver Ⅳ",
    "Silver Ⅲ",
    "Silver Ⅱ",
    "Silver Ⅰ",
    "Gold Ⅳ",
    "Gold Ⅲ",
    "Gold Ⅱ",
    "Gold Ⅰ",
    "Platinum Ⅳ",
    "Platinum Ⅲ",
    "Platinum Ⅱ",
    "Platinum Ⅰ",
    "Emerald Ⅳ",
    "Emerald Ⅲ",
    "Emerald Ⅱ",
    "Emerald Ⅰ",
    "Diamond Ⅳ",
    "Diamond Ⅲ",
    "Diamond Ⅱ",
    "Diamond Ⅰ",
    "Master",
    "Grandmaster",
    "Challenger",
]